### ISSUE TITLE
Convert from binary format

### ISSUE THREAD

**Issue by jaredmoody** [KenjiOhtsuka/chainpoint_gem#12]
Chainpoint provides the [chainpoint-binary](https://github.com/chainpoint/chainpoint-binary) package for converting the binary proof format into JSON.

I'd like to have the functionality of decoding the proof inside my ruby application. I think it might be nice to have this functionality within this gem, but the downside is that it will add dependencies to this gem; `zlib` and `msgpack` are required to decode the binary format.

I'd be happy to submit a PR to add the decoding functionality to this gem if you would like to include it - if not, I'll create a new gem with this functionality.

What do you think?

**Comment by jaredmoody** [comment]
Didn't realize zlib is part of the ruby stdlib, so `msgpack` would be the only additional dependency

**Comment by KenjiOhtsuka** [comment]
It sounds good 👍  @jaredmoody
