### ISSUE TITLE
Return node URI from submit

### ISSUE THREAD

**Issue by jaredmoody** [KenjiOhtsuka/chainpoint_gem#13]
Because the node is selected at random and only the node that a hash was submitted to can retrieve the proof for the hash, it seems very important that the URI of the node that was submitted to be returned from `Chainpoint#submit`

You can see that the [official chainpoint js client does this as well](https://github.com/chainpoint/chainpoint-client-js#submithasheshashes-uris-callback).

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 
Could you update the `README.md` ?

**Comment by jaredmoody** [comment]
#14 did update `README.md`, is there additional information you would like to add?

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 
Oh? but https://github.com/KenjiOhtsuka/chainpoint_gem/pull/14/files shows 1 file difference 🤔

**Comment by jaredmoody** [comment]
Ah, my mistake, I will send another PR
