### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by jaredmoody** [KenjiOhtsuka/chainpoint_gem#18]
There's a `.travis.yml` file in this repository, but Travis CI has not been setup. Once it is setup, PRs can be automatically tested.

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 

Thank you.

I have a question.

What do you think about Circle CI?
Is Travis better?

**Comment by jaredmoody** [comment]
I don't have a preference, I just saw that Travis was already indicated in the repo. I think either would be fine.

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 

`.travis.yml` was automatically generated when I created the project.
I don't have much experience of Travis, so Circle CI is better, but there are not meaningful tests now. 🤔

**Comment by jaredmoody** [comment]
#17 enforces code style which should be run by a CI.

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 

I added Travis badge on README.md.
