### ISSUE TITLE
Redundant Copyright/Legal

### ISSUE THREAD

**Issue by jaredmoody** [KenjiOhtsuka/chainpoint_gem#24]
Is it necessary to have this notice in every file? It adds a lot of clutter.

```
# chainpoint_gem
# Copyright (C) 2019 Kenji Otsuka
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 

I added it because LICENSE recommends to do so.
https://github.com/KenjiOhtsuka/chainpoint_gem/blob/develop/LICENSE

**Comment by jaredmoody** [comment]
OK, I haven't seen other open source projects doing that, but maybe it's specific to GNU GPL 3.0. I don't like it though 😕

**Comment by KenjiOhtsuka** [comment]
@jaredmoody 

Here are examples.
https://github.com/TTimo/doom3.gpl/blob/master/neo/cm/CollisionModel_contents.cpp
https://github.com/librenms/librenms/blob/master/app/Application.php
